# Definition of nodes
# addr address for node
# tls_ca_cert tls cert
peer1: &peer1
  addr: localhost:7051
  org: org1
  #tls_ca_cert: ./organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

# peer2: &peer2
#   addr: localhost:8051
#   org: org2
#   ssl_target_name_override: peer0.org2.trace.com
#   tls_ca_cert: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org2.trace.com/peers/peer0.org2.trace.com/tls/ca.crt

# peer3: &peer3
#   addr: localhost:9051
#   org: org3
#   #tls_ca_cert: ./organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

# peer4: &peer4
#   addr: localhost:10051
#   org: org4
#   #tls_ca_cert: ./organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

# peer5: &peer5
#   addr: localhost:11051
#   org: org5
#tls_ca_cert: ./organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

orderer1: &orderer1
  addr: localhost:7050
  #tls_ca_cert: ./organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

policyFile: ./andLogic.rego

# Peer Nodes to interact with as endorsement Peers
endorsers:
  - *peer1

# Peer Nodes to interact with as Commit Peers as listening
committers:
  - *peer1
# we might support multi-committer in the future for more complex test scenario.
# i.e. consider tx committed only if it's done on >50% of nodes.
# Give your commit Threshold as numbers for peers here.
commitThreshold: 2

# orderer Nodes to interact with
orderer: *orderer1

# Invocation configs
channel: tracechannel
chaincode: drivercc
# chain code args below, in a list of str
# we provides 3 kinds of randmon
# uuid
# randomString$length
# randomNumber$min_$max
args:
  - createTransport
  - uuid
  - uuid
  - chenliang
  - 陈亮司机
  - 18786755678
  - 运输部
  - 2022-10-24 15:23:45
  -
  - 6976922239153213440
  - 中途定位
# Tx submiter information
mspid: Org1MSP
#private_key: ./organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
#sign_cert: ./organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
private_key: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/users/Admin@org1.trace.com/msp/keystore/5e0b4ed6728b3e83577b4a6460c479c40468e44125b70e964f0c11d9630dc1e0_sk
sign_cert: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/users/Admin@org1.trace.com/msp/signcerts/Admin@org1.trace.com-cert.pem
# network traffic control
num_of_conn: 2
client_per_conn: 2
