name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 1.2.0
  Size: 5 Orgs with 5 Peer
  Orderer: Solo
  Distribution: Mutual Host
  StateDB: CouchDB

clients:
  Admin@org1.trace.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/Org1
        cryptoStore:
          path: /tmp/Org1
      clientPrivateKey:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/users/Admin@org1.trace.com/msp/keystore/5e0b4ed6728b3e83577b4a6460c479c40468e44125b70e964f0c11d9630dc1e0_sk
      clientSignedCert:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/users/Admin@org1.trace.com/msp/signcerts/Admin@org1.trace.com-cert.pem

  Admin@org2.trace.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/Org2
        cryptoStore:
          path: /tmp/Org2
      clientPrivateKey:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org2.trace.com/users/Admin@org2.trace.com/msp/keystore/94000312249d103a41c974b0c00b99d9cc579d4184490e1eeaf85e793ba940f6_sk
      clientSignedCert:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org2.trace.com/users/Admin@org2.trace.com/msp/signcerts/Admin@org2.trace.com-cert.pem

  Admin@org3.trace.com:
    client:
      organization: Org3
      credentialStore:
        path: /tmp/Org3
        cryptoStore:
          path: /tmp/Org3
      clientPrivateKey:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org3.trace.com/users/Admin@org3.trace.com/msp/keystore/7c086268307415636ab48277025963cc68d3c43c73c6419b005cb24560d5c52e_sk
      clientSignedCert:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org3.trace.com/users/Admin@org3.trace.com/msp/signcerts/Admin@org3.trace.com-cert.pem

  Admin@org4.trace.com:
    client:
      organization: Org4
      credentialStore:
        path: /tmp/Org4
        cryptoStore:
          path: /tmp/Org4
      clientPrivateKey:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org4.trace.com/users/Admin@org4.trace.com/msp/keystore/53fbcbc782d4dbe78bc7061496ee4f01727c0a120c555303bded52effe498b71_sk
      clientSignedCert:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org4.trace.com/users/Admin@org4.trace.com/msp/signcerts/Admin@org4.trace.com-cert.pem

  Admin@org5.trace.com:
    client:
      organization: Org5
      credentialStore:
        path: /tmp/Org5
        cryptoStore:
          path: /tmp/Org5
      clientPrivateKey:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org5.trace.com/users/Admin@org5.trace.com/msp/keystore/a059b9c092dfbd77e015370721a58f542cf07d7f9a5a76c759b1922d958035e0_sk
      clientSignedCert:
        path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org5.trace.com/users/Admin@org5.trace.com/msp/signcerts/Admin@org5.trace.com-cert.pem

channels:
  tracechannel:
    created: true
    orderers:
      - orderer.trace.com
    peers:
      peer0.org1.trace.com:
        eventSource: true
      peer0.org2.trace.com:
        eventSource: true
      peer0.org3.trace.com:
        eventSource: true
      peer0.org4.trace.com:
        eventSource: true
      peer0.org5.trace.com:
        eventSource: true

    chaincodes:
      - id: drivercc
        version: "1.0"

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.trace.com
    certificateAuthorities:
      - ca.trace.com
    adminPrivateKey:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/users/Admin@org1.trace.com/msp/keystore/5e0b4ed6728b3e83577b4a6460c479c40468e44125b70e964f0c11d9630dc1e0_sk
    signedCert:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/users/Admin@org1.trace.com/msp/signcerts/Admin@org1.trace.com-cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.trace.com
    certificateAuthorities:
      - ca.trace.com
    adminPrivateKey:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org2.trace.com/users/Admin@org2.trace.com/msp/keystore/94000312249d103a41c974b0c00b99d9cc579d4184490e1eeaf85e793ba940f6_sk
    signedCert:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org2.trace.com/users/Admin@org2.trace.com/msp/signcerts/Admin@org2.trace.com-cert.pem

  Org3:
    mspid: Org3MSP
    peers:
      - peer0.org3.trace.com
    certificateAuthorities:
      - ca.trace.com
    adminPrivateKey:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org3.trace.com/users/Admin@org3.trace.com/msp/keystore/7c086268307415636ab48277025963cc68d3c43c73c6419b005cb24560d5c52e_sk
    signedCert:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org3.trace.com/users/Admin@org3.trace.com/msp/signcerts/Admin@org3.trace.com-cert.pem

  Org4:
    mspid: Org4MSP
    peers:
      - peer0.org4.trace.com
    certificateAuthorities:
      - ca.trace.com
    adminPrivateKey:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org4.trace.com/users/Admin@org4.trace.com/msp/keystore/53fbcbc782d4dbe78bc7061496ee4f01727c0a120c555303bded52effe498b71_sk
    signedCert:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org4.trace.com/users/Admin@org4.trace.com/msp/signcerts/Admin@org4.trace.com-cert.pem

  Org5:
    mspid: Org5MSP
    peers:
      - peer0.org5.trace.com
    certificateAuthorities:
      - ca.trace.com
    adminPrivateKey:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org5.trace.com/users/Admin@org5.trace.com/msp/keystore/a059b9c092dfbd77e015370721a58f542cf07d7f9a5a76c759b1922d958035e0_sk
    signedCert:
      path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org5.trace.com/users/Admin@org5.trace.com/msp/signcerts/Admin@org5.trace.com-cert.pem

orderers:
  orderer.trace.com:
    url: grpc://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.trace.com
    # tlsCACerts:
    #   path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/ordererOrganizations/trace.com/msp/tlscacerts/tlsca.trace.com-cert.pem

peers:
  peer0.org1.trace.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.trace.com
      grpc.keepalive_time_ms: 600000
    # tlsCACerts:
    #   path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/msp/tlscacerts/tlsca.org1.trace.com-cert.pem

  # peer0.org2.trace.com:
  #   url: grpc://localhost:8051
  #   grpcOptions:
  #     ssl-target-name-override: peer0.org2.trace.com
  #     grpc.keepalive_time_ms: 600000
  #   # tlsCACerts:
  #   #   path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org2.trace.com/msp/tlscacerts/tlsca.org2.trace.com-cert.pem

  # peer0.org3.trace.com:
  #   url: grpc://localhost:9051
  #   grpcOptions:
  #     ssl-target-name-override: peer0.org3.trace.com
  #     grpc.keepalive_time_ms: 600000
  #   # tlsCACerts:
  #   #   path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org3.trace.com/msp/tlscacerts/tlsca.org3.trace.com-cert.pem

  # peer0.org4.trace.com:
  #   url: grpc://localhost:10051
  #   grpcOptions:
  #     ssl-target-name-override: peer0.org4.trace.com
  #     grpc.keepalive_time_ms: 600000
  #   # tlsCACerts:
  #   #   path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org4.trace.com/msp/tlscacerts/tlsca.org4.trace.com-cert.pem

  # peer0.org5.trace.com:
  #   url: grpc://localhost:11051
  #   grpcOptions:
  #     ssl-target-name-override: peer0.org5.trace.com
  #     grpc.keepalive_time_ms: 600000
  #   # tlsCACerts:
  #   #   path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org5.trace.com/msp/tlscacerts/tlsca.org5.trace.com-cert.pem

certificateAuthorities:
  ca.trace.com:
    url: http://localhost:7054
    httpOptions:
      verify: true
    # tlsCACerts:
    # path: /root/work/repos/gorepos/src/github.com/nk-akun/blockchain-trace/blockchain-trace-bcnetwork/basic-network/crypto-config/peerOrganizations/org1.trace.com/ca/ca.org1.trace.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
